// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package pgstore

import (
	"time"

	"github.com/google/uuid"
)

type Message struct {
	ID            uuid.UUID
	RoomID        uuid.UUID
	Message       string
	ReactionCount int64
	Answered      bool
	AuthorID      string
	AuthorName    string
	CreatedAt     time.Time
}

type Room struct {
	ID    uuid.UUID
	Theme string
}
